// <auto-generated />
using System;
using CollegeManagement.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CollegeManagement.DataLayer.Migrations
{
    [DbContext(typeof(CollegeDbContext))]
    [Migration("20230616165630_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CollegeManagement.Entities.Department", b =>
                {
                    b.Property<long>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CollegeManagement.Entities.Student", b =>
                {
                    b.Property<long>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DepartmentNameDepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("DepartmentNameDepartmentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CollegeManagement.Entities.Teacher", b =>
                {
                    b.Property<long>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DepartmentNameDepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.HasIndex("DepartmentNameDepartmentId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("CollegeManagement.Entities.Student", b =>
                {
                    b.HasOne("CollegeManagement.Entities.Department", "DepartmentName")
                        .WithMany()
                        .HasForeignKey("DepartmentNameDepartmentId");
                });

            modelBuilder.Entity("CollegeManagement.Entities.Teacher", b =>
                {
                    b.HasOne("CollegeManagement.Entities.Department", "DepartmentName")
                        .WithMany()
                        .HasForeignKey("DepartmentNameDepartmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
